### ISSUE TITLE
How do I build this application?

### ISSUE THREAD

**Issue by neontapir** [RallyCommunity/PortfolioDrilldownApp#8]
From looking at the other projects in RallyCommunity, it seems plausible that there's a 'grunt build' task missing in Gruntfile.js. Is this correct, or is the application compiled in a different way?

**Comment by RallyRonnie** [comment]
We usually use the Rally App Builder (https://github.com/RallyApps/rally-app-builder)

**Comment by neontapir** [comment]
Thanks!
